package dao;

import static dao.DAOUtility.silentClosures;
import static dao.DAOUtility.PreparedRequestInitialization;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import org.joda.time.DateTime;

import beans.Question;
import beans.Survey;

public class QuestionDaoImpl implements QuestionDao 
{
	private static final String SURVEYACTIVE	  					= "active";
	
    private static final String SQL_SELECT        					= "SELECT id, sujet, actif, createdAt FROM questionnaire ORDER BY id";
    private static final String SQL_SELECT_BY_ID	 				= "SELECT id, sujet, actif, createdAt FROM questionnaire WHERE id = ?";
    private static final String SQL_INSERT        					= "INSERT INTO question (idQuestionnaire, intitule, ordre, actif) VALUES (?, ?, ?, ?)";
    private static final String SQL_UPDATE        					= "UPDATE questionnaire SET sujet = ?, actif = ? WHERE id = ?";
    private static final String SQL_DELETE_BY_ID 					= "DELETE FROM questionnaire WHERE id = ?";
    private static final String SQL_SELECT_SURVVEY_BY_ID			= "SELECT id, sujet, actif, createdAt FROM questionnaire WHERE id = ?";
    private static final String SQL_SELECT_QUESTION_BY_SURVEY_ID	= "SELECT idQuestion, idQuestionnaire, intitule, ordre, actif FROM question WHERE idQuestionnaire = ? ORDER BY ordre";
    
    private DAOFactory          daoFactory;

    QuestionDaoImpl( DAOFactory daoFactory ) 
    {
        this.daoFactory = daoFactory;
    }

    /* Implémentation de la méthode définie dans l'interface ClientDao */
    @Override
    public Question find( Long lId ) throws DAOException 
    {
        return find( SQL_SELECT_BY_ID, lId );
    }

    /* Implémentation de la méthode définie dans l'interface ClientDao */
    @Override
    public void create( Question question ) throws DAOException 
    {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet AutoGeneratedValues = null;

        try 
        {
        	connection = daoFactory.getConnection();
        	boolean bActive = false;
        	String sStatus = question.getActive();
        	if(sStatus.equals( SURVEYACTIVE )) 
        	{
        		bActive = true;
        	}
            preparedStatement = PreparedRequestInitialization( connection, SQL_INSERT, true, question.getSurvey().getId(),
            		question.getText(), question.getOrder(), bActive);
            int status = preparedStatement.executeUpdate();
            if ( status == 0 ) 
            {
                throw new DAOException( "Échec de la création du client, aucune ligne ajoutée dans la table." );
            }
            /*Peut être utile pour les questions et les réponses */
            AutoGeneratedValues = preparedStatement.getGeneratedKeys();
            if ( AutoGeneratedValues.next() ) 
            {
            	question.setId( AutoGeneratedValues.getLong( 1 ) );
            } 
            else 
            {
                throw new DAOException( "Échec de la création du client en base, aucun ID auto-généré retourné." );
            }
            
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( AutoGeneratedValues, preparedStatement, connection );
        }
    }
    
    /* Implémentation de la méthode définie dans l'interface ClientDao */
    @Override
    public void modify( Question question ) throws DAOException 
    {
        Connection connection = null;
        PreparedStatement preparedStatement = null;

        try 
        {
        	connection = daoFactory.getConnection();
        	boolean bActive = false;
        	String sStatus = question.getActive();
        	if(sStatus.equals( SURVEYACTIVE )) 
        	{
        		bActive = true;
        	}
            preparedStatement = PreparedRequestInitialization( connection, SQL_UPDATE, true,
            		question.getText(),  bActive, question.getId());
            int status = preparedStatement.executeUpdate();
            if ( status == 0 ) 
            {
                throw new DAOException( "Échec de la création du client, aucune ligne ajoutée dans la table." );
            }
            
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( preparedStatement, connection );
        }
    }

    /* Implémentation de la méthode définie dans l'interface ClientDao */
    @Override
    public List<Question> lister(Long lSurveyId) throws DAOException 
    {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Question> questions = new ArrayList<Question>();

        try 
        {
            connection = daoFactory.getConnection();
            preparedStatement = PreparedRequestInitialization( connection, SQL_SELECT_QUESTION_BY_SURVEY_ID, false, lSurveyId );
            resultSet = preparedStatement.executeQuery();
            while ( resultSet.next() ) 
            {
                questions.add( map( resultSet ) );
            }
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( resultSet, preparedStatement, connection );
        }

        return questions;
    }

    /* Implémentation de la méthode définie dans l'interface ClientDao */
    @Override
    public void delete( Question question ) throws DAOException 
    {
        Connection connection = null;
        PreparedStatement preparedStatement = null;

        try 
        {
        	connection = daoFactory.getConnection();
            preparedStatement = PreparedRequestInitialization( connection, SQL_DELETE_BY_ID, true, question.getId() );
            int statut = preparedStatement.executeUpdate();
            if ( statut == 0 ) 
            {
                throw new DAOException( "Échec de la suppression du questionnaire, aucune ligne supprimée de la table." );
            } 
            else 
            {
                question.setId( null );
            }
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( preparedStatement, connection );
        }
    }

    /*
     * Méthode générique utilisée pour retourner un client depuis la base de
     * données, correspondant à la requête SQL donnée prenant en paramètres les
     * objets passés en argument.
     */
    private Question find( String sql, Object... objects ) throws DAOException 
    {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        Question question = null;

        try 
        {
            /* Récupération d'une connexion depuis la Factory */
        	connection = daoFactory.getConnection();
            /*
             * Préparation de la requête avec les objets passés en arguments
             * (ici, uniquement un id) et exécution.
             */
            preparedStatement = PreparedRequestInitialization( connection, sql, false, objects );
            resultSet = preparedStatement.executeQuery();
            /* Parcours de la ligne de données retournée dans le ResultSet */
            if ( resultSet.next() ) 
            {
            	question = map( resultSet );
            }
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( resultSet, preparedStatement, connection );
        }

        return question;
    }
    
    private Survey findSurvey( String sql, Object... objects ) throws DAOException 
    {
    	
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        Survey survey = new Survey();

        try 
        {
            /* Récupération d'une connexion depuis la Factory */
        	connection = daoFactory.getConnection();
            /*
             * Préparation de la requête avec les objets passés en arguments
             * (ici, uniquement un id) et exécution.
             */
            preparedStatement = PreparedRequestInitialization( connection, sql, false, objects );
            resultSet = preparedStatement.executeQuery();
            /* Parcours de la ligne de données retournée dans le ResultSet */
            if ( resultSet.next() ) 
            {
                survey.setId(resultSet.getLong("id"));
                survey.setSubject(resultSet.getString("sujet"));
                if(resultSet.getInt("actif") == 1)
                {
                	survey.setActive(true);
                }
                else
                {
                	survey.setActive(false);
                }
                
                survey.setCreationDate( new DateTime( resultSet.getTimestamp( "createdAt" ) ) );
            }
        } 
        catch ( SQLException e ) 
        {
            throw new DAOException( e );
        } 
        finally 
        {
            silentClosures( resultSet, preparedStatement, connection );
        }

        return survey;
    }

    private Object getServletContext() {
		// TODO Auto-generated method stub
		return null;
	}

	/*
     * Simple méthode utilitaire permettant de faire la correspondance (le
     * mapping) entre une ligne issue de la table des clients (un ResultSet) et
     * un bean Client.
     */
    private Question map( ResultSet resultSet ) throws SQLException 
    {
        Question question = new Question();
        question.setId(resultSet.getLong("idQuestion"));
        question.setText(resultSet.getString("intitule"));
        question.setOrder(resultSet.getLong("ordre"));
        if(resultSet.getInt("actif") == 1)
        {
        	question.setActive(true);
        }
        else
        {
        	question.setActive(false);
        }
        
        Survey survey = findSurvey(SQL_SELECT_SURVVEY_BY_ID, resultSet.getLong("idQuestionnaire"));
        question.setSurvey(survey);
        
        return question;
        /*
        client.setId( resultSet.getLong( "id" ) );
        client.setNom( resultSet.getString( "nom" ) );
        client.setPrenom( resultSet.getString( "prenom" ) );
        client.setAdresse( resultSet.getString( "adresse" ) );
        client.setTelephone( resultSet.getString( "telephone" ) );
        client.setEmail( resultSet.getString( "email" ) );
        client.setImage( resultSet.getString( "image" ) );
        return client;
        */
    }

}